# Generated by Django 6.0.3 on 2026-03-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('occasion', models.CharField(max_length=64)),
                ('mood_tone', models.CharField(max_length=64)),
                ('genre', models.CharField(max_length=64)),
                ('singer_voice', models.CharField(max_length=256)),
                ('meaning', models.CharField(max_length=256)),
                ('song_durations', models.TimeField()),
            ],
        ),
    ]
