# Generated by Django 6.0.3 on 2026-04-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_path',
            field=models.CharField(blank=True, help_text='Folder path where the song is stored', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='song',
            name='strategy',
            field=models.CharField(choices=[('mock', 'Mock'), ('suno', 'Suno')], default='mock', max_length=10),
        ),
        migrations.AlterField(
            model_name='song',
            name='singer_voice',
            field=models.CharField(max_length=64),
        ),
    ]
