# Generated by Django 6.0.3 on 2026-04-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_song_song_path_song_status_song_strategy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='status',
        ),
        migrations.AddField(
            model_name='song',
            name='generation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='song',
            name='singer_voice',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_path',
            field=models.CharField(blank=True, help_text='Folder path where the song is stored (e.g., storage/song/song_id)', max_length=512, null=True),
        ),
    ]
