# Generated by Django 6.0.3 on 2026-04-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_remove_song_status_song_generation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_url',
            field=models.CharField(blank=True, help_text='Path or URL to the generated audio file', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='task_id',
            field=models.CharField(blank=True, help_text='External API task ID (e.g., Suno API task ID)', max_length=256, null=True),
        ),
    ]
